-- Schéma initial de l'application, tel qu'il existait sur H2 (bascule PostgreSQL, cf.
-- docs/postgresql-migration.md). Généré depuis la structure réelle produite par Hibernate
-- (ddl-auto=create contre une base PostgreSQL vide), puis nettoyé pour Flyway — c'est la
-- dernière fois que le schéma est dérivé automatiquement des entités : à partir d'ici, toute
-- évolution de schéma passe par une nouvelle migration versionnée (V2__..., etc.), jamais par un
-- retour à ddl-auto=update.

CREATE TABLE public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255),
    nom character varying(255) NOT NULL,
    numerocni character varying(255),
    password character varying(255) NOT NULL,
    prenom character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    telephone character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ROLE_LOCATAIRE'::character varying, 'ROLE_ADMIN'::character varying, 'ROLE_SECRETARIAT'::character varying, 'ROLE_COMPTABLE'::character varying])::text[]))),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_telephone_key UNIQUE (telephone)
);

CREATE TABLE public.emplacements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prix numeric(12,2) NOT NULL,
    superficie numeric(10,2) NOT NULL,
    added_at timestamp(6) without time zone NOT NULL,
    categorie character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    palier character varying(255) NOT NULL,
    statut character varying(255) NOT NULL,
    CONSTRAINT emplacements_categorie_check CHECK (((categorie)::text = ANY ((ARRAY['BOUTIQUE'::character varying, 'MAGASIN'::character varying])::text[]))),
    CONSTRAINT emplacements_palier_check CHECK (((palier)::text = ANY ((ARRAY['PALIER_1'::character varying, 'PALIER_2'::character varying, 'PALIER_3'::character varying])::text[]))),
    CONSTRAINT emplacements_statut_check CHECK (((statut)::text = ANY ((ARRAY['DISPONIBLE'::character varying, 'NON_DISPONIBLE'::character varying, 'EN_MAINTENANCE'::character varying])::text[])))
);

CREATE TABLE public.contrats (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_debut date NOT NULL,
    date_fin date NOT NULL,
    date_preavis date,
    duree_caution_mois integer NOT NULL,
    duree_loyer_mois integer NOT NULL,
    montant_caution numeric(12,2) NOT NULL,
    montant_loyer numeric(12,2) NOT NULL,
    contrat_precedent_id bigint,
    emplacement_id bigint NOT NULL,
    locataire_id bigint NOT NULL,
    motif_resiliation character varying(1000),
    termes character varying(1000),
    activite character varying(255),
    nom_enseigne character varying(255),
    statut character varying(255) NOT NULL,
    CONSTRAINT contrats_statut_check CHECK (((statut)::text = ANY ((ARRAY['VALIDER'::character varying, 'EN_ATTENTE'::character varying, 'REJETER'::character varying, 'RESILIER'::character varying])::text[]))),
    CONSTRAINT fk_contrats_emplacement FOREIGN KEY (emplacement_id) REFERENCES public.emplacements(id),
    CONSTRAINT fk_contrats_locataire FOREIGN KEY (locataire_id) REFERENCES public.users(id),
    CONSTRAINT fk_contrats_contrat_precedent FOREIGN KEY (contrat_precedent_id) REFERENCES public.contrats(id)
);

CREATE TABLE public.echeances (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_echeance date NOT NULL,
    montant_du numeric(12,2) NOT NULL,
    contrat_id bigint NOT NULL,
    statut character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT echeances_statut_check CHECK (((statut)::text = ANY ((ARRAY['EN_COURS'::character varying, 'PAYEE'::character varying, 'EN_RETARD'::character varying])::text[]))),
    CONSTRAINT echeances_type_check CHECK (((type)::text = ANY ((ARRAY['LOYER'::character varying, 'CAUTION'::character varying])::text[]))),
    CONSTRAINT fk_echeances_contrat FOREIGN KEY (contrat_id) REFERENCES public.contrats(id)
);

CREATE TABLE public.paiements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_paiement date NOT NULL,
    montant_paye numeric(12,2) NOT NULL,
    admin_enregistrant_id bigint NOT NULL,
    echeance_id bigint NOT NULL,
    CONSTRAINT fk_paiements_admin_enregistrant FOREIGN KEY (admin_enregistrant_id) REFERENCES public.users(id),
    CONSTRAINT fk_paiements_echeance FOREIGN KEY (echeance_id) REFERENCES public.echeances(id)
);

CREATE TABLE public.journal_audit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_action timestamp(6) without time zone NOT NULL,
    entite_id bigint NOT NULL,
    utilisateur_id bigint NOT NULL,
    ancienne_valeur character varying(2000),
    nouvelle_valeur character varying(2000),
    nom_entite character varying(255) NOT NULL,
    type_action character varying(255) NOT NULL,
    CONSTRAINT journal_audit_type_action_check CHECK (((type_action)::text = ANY ((ARRAY['CREATION'::character varying, 'MODIFICATION'::character varying, 'SUPPRESSION'::character varying, 'ANNULATION'::character varying])::text[]))),
    CONSTRAINT fk_journal_audit_utilisateur FOREIGN KEY (utilisateur_id) REFERENCES public.users(id)
);

CREATE TABLE public.documents_joints (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ajoute_le timestamp(6) without time zone NOT NULL,
    entite_id bigint NOT NULL,
    chemin_stockage character varying(255) NOT NULL,
    nom_entite character varying(255) NOT NULL
);
